- name: Ensure SELinux is permissive
  selinux:
    policy: targeted
    state: permissive

- name: Update HTTPD config
  template:
    src: httpd.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
  - Restart HTTPD

- name: Create sample info page 
  copy:
    src: info.html 
    dest: /var/www/html/info.html

