- name: Install HTTPD
  package:
    name: httpd
    state: present

- name: Starting HTTP
  service:
    name: httpd
    state: started

- name: Enabling HTTP
  service:
    name: httpd
    enabled: true

